### ISSUE TITLE
XbyK Lucene Search null point error

### ISSUE THREAD

**Issue by phixxo** [Kentico/xperience-by-kentico-lucene#27]
Unable to integrate Lucene search into XbK - admin UI throws an error.

- Installed fresh DancingGoat template website for version 28.2.0
- Restored the template database with kentico-xperience-dbmanager 
- Run the website to test it, and everything worked well.
------Search module does not exist yet.
- Installed the nuget package Kentico.Xperience.Lucene 4.0.0
 When I run the project again (by using IIS Express from VS) I got the following error message:

![image](https://github.com/Kentico/xperience-by-kentico-lucene/assets/17883073/619afda7-60d2-4398-bf30-e8ce66cd8c05)

- I quickly add the lucene code into Program.cs file
![image](https://github.com/Kentico/xperience-by-kentico-lucene/assets/17883073/b1c0b6b3-fe66-46d7-a869-7160d146e35e)

- Code from previous step solved the live site issue that I previous had and I was able to boot up website. I saw in event log that classes were created for Lucene Module, I was able to confirm the same in the database (saw tables) and I was able to see the 'Search' module on dashboard.
![image](https://github.com/Kentico/xperience-by-kentico-lucene/assets/17883073/923e39c4-b933-47fe-bc68-861f45106d6e)

When I clicked to the module, I get the 500 error (can't open module at all, issue occur on every click), which is the reason why I'm reaching out here. You can find the errors attached
[err_1.txt](https://github.com/Kentico/xperience-by-kentico-lucene/files/14110562/err_1.txt)
[err_2.txt](https://github.com/Kentico/xperience-by-kentico-lucene/files/14110563/err_2.txt)

**Comment by seangwright** [comment]
We have several updates that need to be made to improve the module installation process. Hopefully we can get those tested, merged, and published soon.

**Comment by seangwright** [comment]
@phixxo could you try [4.1.0-prelease-1](https://www.nuget.org/packages/Kentico.Xperience.Lucene/4.1.0-prerelease-1)?

You shouldn't need to modify anything in the database or change your code (but you will get some warnings for obsolete APIs and instructions on what to replace them with)
