### ISSUE TITLE
Feature: Update existing index configuration when possible

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-lucene#29]
### Motivation

We currently [delete all related data for an index](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene/Admin/DefaultLuceneConfigurationStorageService.cs#L155) when it's updated and [create new relationships](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene/Admin/DefaultLuceneConfigurationStorageService.cs#L166) from the submitted configuration.

While this works, it is noisy in Xperience's CI repository - adding 1 index path will delete all languages, channels, and paths for an index.

This also makes more difficult to use CD because removing the deleted objects will require [a RestoreMode of Full](https://docs.xperience.io/xp/developers-and-admins/ci-cd/continuous-deployment#ContinuousDeployment-GenerateCDconfigurationfiles) which isn't compatible with most PROD environments after an initial release.

### Proposed solution

We should track the identifiers of the related objects in the [LuceneIndexConfigurationComponent](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene/Admin/Components/LuceneIndexConfigurationComponent.cs) and use that to update items that already exist, only deleting when appropriate.

### Additional context

I saved a search index without making any changes to it and this is the result in the CI repository.

![image](https://github.com/Kentico/xperience-by-kentico-lucene/assets/1382768/10ecd8b6-1195-4297-8d5e-0bf60a29d63d)

The paths that were deleted locally will need to also be deleted in non-local environments, except manually.

**Comment by liparova** [comment]
Thank you for your recommendation. We'll evaluate its feasibility and provide regular updates on its integration progress.

**Comment by DavidSlavik** [comment]
Approved for development.

**Comment by bkapustik** [comment]
We have created GitHub release v7.0.0 which enhances this integration with index configuration. Items no longer get  deleted when it is not necessary
