### ISSUE TITLE
Search index updates aren't triggered if included content type entries contain whitespace

### ISSUE THREAD

**Issue by bluemodus-tbuchanan** [Kentico/xperience-by-kentico-lucene#33]
### Brief bug description

We noticed certain page types were not triggering search index updates when the page was updated. After investigating we noticed that there was whitespace after a line item in the included content types of the index path. We removed the additional whitespace from the line item and edited the page again and saw the index update as expected.

### Repro steps

1. Create or edit a page search index at `/admin/lucene/indexes`
2. In the "Included ContentType Items" field include an entry with extra whitespace after the item (in our instance the type that failed to trigger an update was at the end of the list)
3. Save the path, save the index, and observe the last updated time of the index
4. Edit a page's content (in our instance, we are updating the url of the page)
5. Head back to the indexes and observe the last updated time

### Expected behavior

After waiting a reasonable amount of time for the index to update, the index last updated time should be after the page last updated time and the page that was modified returns it's new data in the results

### Test environment

 - Platform/OS: 
   - net6.0
   - Windows 10
 - Browser
   - Chrome
 - Version
   - Xperience by Kentico version 28.1.0
   - Kentico.Xperience.Lucene 4.1.0

### Screenshots
The configuration we had that caused the issue, with client codename omitted.
![image](https://github.com/Kentico/xperience-by-kentico-lucene/assets/99774690/6a2e4e7e-610e-4aab-b35c-f7ab82f9de0b)

**Comment by fialafilip** [comment]
We are working on fix, which will change input type from text area to multiselect.

**Comment by fialafilip** [comment]
Hi @bluemodus-tbuchanan, fix has been released in v5.0.0.0
https://github.com/Kentico/xperience-by-kentico-lucene/releases
