### ISSUE TITLE
LuceneIndex has hard-coded StandardAnalyzer

### ISSUE THREAD

**Issue by BS-jiriceska** [Kentico/xperience-by-kentico-lucene#40]
### Motivation

When I want to build index for Kentico, I'd like to cover some specifics (e.g. diacritics, umlaut and so on) of desired language by picking adequate Analyzer and not rely on preset StandardAnalyzer. 
Standard analyzer does not correctly work with diacritics (I'd like to find "über" either as "über" and "uber").

### Proposed solution

I'd like to add arbitrary analyzers during service registration (probably via new method RegisterAnalyzer on ILuceneBuilder) and then pick appropriate analyzer along with indexing strategy in Kentico admin.
I expect to have possibility to obtain selected analyzer in code.

**Comment by liparova** [comment]
Thank you for highlighting this request. We will review it internally and keep you informed of any developments.

**Comment by DavidSlavik** [comment]
Approved for development.

**Comment by bkapustik** [comment]
We have created GitHub release v7.0.0 which enhances this integration with Lucene Analyzer selection.
