### ISSUE TITLE
Support multiple sets of facets

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-lucene#49]
**Is your feature request related to a problem? Please describe.**
The [LuceneSearchResultModel](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene.Core/Search/LuceneSearchResultModel.cs#L14) only supports a single facet value, which means if an index includes multiple faceted values a user filters on, there isn't a good way to represent that in the result model class.

Example: Coffee Flavor and Coffee Type could be 2 completely separate facets that could be filtered on independently.

**Describe the solution you'd like**
If a search index includes multiple faceted properties then the search results make it possible to represent multiple facets being filtered for a search operation.

**Describe alternatives you've considered**
I could avoid using the `LuceneSearchResultModel` and create a custom model if the `LuceneSearchResultModel` is intended only for "simple" single facet scenarios.

**Additional context**
I think `LuceneSearchResultModel.Facet` should be combined with `LuceneSearchResultModel.Facets` as a `Dictionary<string, LabelAndValue[]>` where each entry in the dictionary is all the facet result values for each faceted property.

In the simple case, `LuceneSearchResultModel.Facets` would have 1 entry for the single faceted property.

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We'll examine it internally and keep you updated on our progress.

**Comment by bkapustik** [comment]
The `LuceneSearchResultModel.Facet` is just a string that holds the URL facet parameter. It can contain multiple facet parameters. It has no effect on `LuceneSearchResultModel.Facets`. On the other hand, the `LuceneSearchResultModel` is only meant for a simple scenario. It does not have to be used, because the `ILuceneSearchService` defines generic methods where you can use your custom model. I think the dictionary would add a little more complexity and would make the learning curve steeper. I think we should keep the simpler option and maybe add the dictionary to another more complex model.

**Comment by michalJakubis** [comment]
> The `LuceneSearchResultModel.Facet` is just a string that holds the URL facet parameter. It can contain multiple facet parameters. It has no effect on `LuceneSearchResultModel.Facets`. On the other hand, the `LuceneSearchResultModel` does not have to be used because the `ILuceneSearchService` defines generic methods where you can use your custom model. The `LuceneSearchResultModel.Facets` is there only to show number of hits per facet. I think if you want to represent a number of hits per each category per each facet, you can just create a `LabelAndValue` instance.
> 
> For example: Label: Coffee Flavor-Bitter, Value:3; Label: Coffee Flavor-Sweet, Value:2; and the same for Coffee Type. I don't see the problem.

@seangwright What do you think?

**Comment by seangwright** [comment]
Yeah, this makes sense. I think handling the simple case with `LuceneSearchResultModel` is the best approach since developers can replace it with a completely custom type to meet different requirements.
