### ISSUE TITLE
Unable to rebuild lucene index - Linux 

### ISSUE THREAD

**Issue by radekzitta** [Kentico/xperience-by-kentico-lucene#56]
**Describe the bug**
My XbK app is hosted in Azure Web App on Linux. When I try to rebuild my lucene index, sometimes an error is displayed and a new record is created in the Event log - see the attached screenshot.  There is an invalid path to the **trash** directory, which is costructed in the 
GenerationStorageStrategy class, ScheduleRemoval method.

**To Reproduce**
1. Host your web app on Linux
2. Click on the Rebuild action button for some search index

**Expected behavior**
Index is rebuild without any issues, even on Linux.

**Screenshots**
![error](https://github.com/Kentico/xperience-by-kentico-lucene/assets/21053244/a238b56b-80d1-4454-8f24-7692b45bfb84)

**Library Version**
7.0.0

**Comment by liparova** [comment]
Hi, thank you for notifying us of the issue. We will proceed to troubleshoot and keep you updated on our analysis.

**Comment by michalJakubis** [comment]
Hi @radekzitta , fix has been released in [v7.0.1](https://github.com/Kentico/xperience-by-kentico-lucene/releases/tag/v7.0.1)
https://github.com/Kentico/xperience-by-kentico-lucene/releases

**Comment by radekzitta** [comment]
> Hi @radekzitta , fix has been released in [v7.0.1](https://github.com/Kentico/xperience-by-kentico-lucene/releases/tag/v7.0.1)

perfect, thank you!
