### ISSUE TITLE
Multilingual indexing - documents of all languages but one deleted in index due to shared itemGuid

### ISSUE THREAD

**Issue by kentico-zdenekc** [Kentico/xperience-by-kentico-lucene#58]
**Describe the bug**
Indexing of webpages translated into multiple languages seems to only store 1 language version for a page/item and deletes Lucene documents of other language versions in the index. Single Lucene document is only of single language, and as the Xperience content items are recognized using itemGuid (common for all lang.versions), the previously created ones are deleted in the index. 
Is that expected behavior if you allow multiple languages for the index in Xperience? Or how should one adjust the code/setup/configuration properly for multilingual in current implementation?

**To Reproduce**
On XbyK instance with sample DancingGoat site,
1. Set up e.g. example indexing (from /xperience-by-kentico-lucene/tree/main/examples/DancingGoat/Search)
2. Create and configure an index e.g. for Article page type, with both English and Spanish languages
3. Rebuild the index
4. See number of indexed documents being 5 (6 articles, 1 single language is secured so is not indexed, 2 of other ones are multilingual). Inspect the actual documents e.g. using lucene tool (Luke) with their data.

**Expected behavior**
With previous steps, 7 indexed documents (5 in En lang., 2 in Es lang.) could be expected. 
Generally, indexing either creates separate Lucene documents for different language versions of an Xperience page (or content item), or, the multilingual content is present within one Lucene document (doesn't seem preferable).

**Library Version**
Xperience by Kentico 29.1.5, xperience-by-kentico-lucene 7.0.1

**Additional context**
When indexing, after finding an existing item GUID  (part of base properties):
[https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene.Core/Indexing/DefaultLuceneTaskProcessor.cs#L135C9-L135C110](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene.Core/Indexing/DefaultLuceneTaskProcessor.cs#L135C9-L135C110)
the code in [https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene.Core/Indexing/DefaultLuceneClient.cs#L27](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/src/Kentico.Xperience.Lucene.Core/Indexing/DefaultLuceneClient.cs#L275) 
deletes existing document, the code comment says:
 
                            // for now all changes are creates, update to be done later
                            // delete old document, there is no upsert nor update in Lucene

**Comment by michalJakubis** [comment]
Hi @kentico-zdenekc , fix has been released in [v7.0.2](https://github.com/Kentico/xperience-by-kentico-lucene/releases/tag/v7.0.2)
