### ISSUE TITLE
Lucene search indexes not being saved to blob storage when custom storage initializer/provider is set

### ISSUE THREAD

**Issue by ant-butcher-mmt** [Kentico/xperience-by-kentico-lucene#60]
**Describe the bug**
When running in a load balanced environment we would want the search indexes to be stored to a shared storage medium i.e. blob storage.

**To Reproduce**
I have a custom module with the following code which should map where lucene indexes are stored into a blob storage container
Go into Development > Search and choose to rebuild an index
```
        var luceneStorage = AzureStorageProvider.Create();
        luceneStorage.PublicExternalFolderObject = true;
        luceneStorage.CustomRootPath = "mediacontainer";
        StorageHelper.MapStoragePath("~/App_Data/LuceneSearch", luceneStorage);
```

**Expected behavior**
Indexes are saved into blob storage.

Current using Kentico.Xperience.Lucene 6.1.0
Kentico.Xperience.Core 29.0.2

We have configured media library storage to store to blob storage using:
```
        var mediaProvider = AzureStorageProvider.Create();
        mediaProvider.CustomRootPath = "mediacontainer";
        mediaProvider.PublicExternalFolderObject = true;
        StorageHelper.MapStoragePath("~/assets/media", mediaProvider);
```
Which does work as expected

**Comment by liparova** [comment]
Hi, thank you for bringing this to our attention. We will investigate and keep you informed of our progress.

**Comment by DavidSlavik** [comment]
Hello there,

I'm sorry for your troubles, but unfortunately, this is not a supported scenario.

We are considering whether to place this extension on the roadmap. We'll keep you posted.

**Comment by DavidSlavik** [comment]
Hello,

We would have to fork Lucene.NET and create customized source code. Instead, we decided to introduce support for web farms.

You can expect this to come by the end of this week.
