### ISSUE TITLE
Unpublishing event is not registered and handled 

### ISSUE THREAD

**Issue by Felwick** [Kentico/xperience-by-kentico-lucene#64]
**Description:**

Unpublished or archived pages are still part of the index content regardless of them being in unpublished state. 

**Reproduction steps:** 

1. Create a page with unique name and information and publish it
2. Search this page and confirm it is in the index
3. Unpublish the page 
4. Check that the page can be still looked up in the index via search

**Expected behavior:**

Page should be removed from index by task when it is unpublished. 

**More details:**

It seems that even though DefaultLuceneTaskLogger is expecting unpublish or archive events to come through in order to log tasks, LuceneSearchModule is only registering event delegate for these specific events:

        WebPageEvents.Publish.Execute += HandleEvent;
        WebPageEvents.Delete.Execute += HandleEvent;
        ContentItemEvents.Publish.Execute += HandleContentItemEvent;
        ContentItemEvents.Delete.Execute += HandleContentItemEvent;

**Library Version**

Kbank site on 7.0.1

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We will investigate and keep you informed of our progress.
