### ISSUE TITLE
Unpublished Web Pages are not removed from the search index

### ISSUE THREAD

**Issue by bluemodus-gshepherd** [Kentico/xperience-by-kentico-lucene#66]
**Describe the bug**
When a Content Editor unpublishes a web page, that web page is not removed from the search index.

Currently:
1. The web page remains in the search index through cache clears.
2. Explicitly rebuilding the search index **properly removes** the web page form the index (Development -> Search -> Rebuild).

From my testing I think the cause stems from Kentico:
1. Not listening to the `WebPageEvents.Unpublish` event.
2. Not looking for the `WebPageEvents.Unpublish.Name` to produce a `LuceneTaskType.DELETE` task (in screenshots).

**To Reproduce**
1. Go to any publishable page
3. Confirm the page is published
4. Click on the dropdown next to "EDIT PAGE"
5. Click on "Unpublish options"
6. Click on "Unpublish now"
7. Perform a content search
8. See the unpublished web page in the search results

**Expected behavior**
The unpublished web page does not appear in the search results.

**Screenshots**
![image](https://github.com/user-attachments/assets/da4fd4ae-2424-4a67-990f-267f53689af5)

**Library Version**
Kentico.Xperience.Lucene 7.0.0
Lucene.Net 4.8.0-beta00016

**Desktop (please complete the following information):**
- N/A

**Smartphone (please complete the following information):**
- N/A

**Additional context**

Our workaround was to listen to the `WebPageEvents.Unpublish` event and send the `WebPageEvents.Delete.Name` to `DefaultLuceneTaskLogger`.

Our project implements a custom indexing strategy, which inherits from `DefaultLuceneIndexingStrategy`, but the `MapToLuceneDocumentOrNull` is never called in the scenario above.

Our project only has a single index. I did not test for multiple indexes.

**Comment by bkapustik** [comment]
Hello, the issue has been fixed in the pull request #67
