### ISSUE TITLE
Channel Indexes contain non-channel Web Pages after they are Published

### ISSUE THREAD

**Issue by bluemodus-gshepherd** [Kentico/xperience-by-kentico-lucene#68]
**Describe the bug**
When publishing a Web Page under a specific channel, that Web Page appears in search indexes not designated for the channel the Web Page was published under.

Search indexes **appropriately exclude** the Web Page when manually rebuilding the index (Development -> Search -> Rebuild).

**To Reproduce**
1. Confirm you have configured at least 2 channels, Channel A and Channel B, for your instance.
2. Confirm you have a search index configured for Channel A.
3. Create and/or Publish a Web Page for Channel B
4. Perform a Search against the search index
5. See the Web Page published on Channel B appear in the results for Channel A

**Expected behavior**
The Web Page published in Channel B does not appear in the results for a search index configured for Channel A.

**Screenshots**

**Library Version**
Library Version
Kentico.Xperience.Lucene 7.0.0
Lucene.Net 4.8.0-beta00016

**Desktop (please complete the following information):**
- N/A

**Smartphone (please complete the following information):**
- N/A

**Additional context**
From my testing I didn't see a place where the Index's channel was compared against the `IndexEventWebPageItemModel.WebsiteChannelName`.

`DefaultLuceneTaskLogger` has a condition to see if the Web Page can be indexed by a specific index name (`IndexedItemModelExtensions.IsIndexedByIndex(...)`), but this always returned `true` and therefore did not prevent the item from being indexed. The method has access to both a retrieved index and the `IndexEventWebPageItemModel` channel names to compare and seemed like an adequate spot.

Our workaround was to configure a hard-coded string with the site code name and check it within a Custom Indexing strategy that we configured on the Index.

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We will investigate and keep you informed of our progress.

**Comment by bkapustik** [comment]
Fixed in pr #71
