### ISSUE TITLE
Old index files should be overwritten during/after a rebuild

### ISSUE THREAD

**Issue by TomaszSkubida** [Kentico/xperience-by-kentico-lucene#74]
The files in the /LuceneSearch folder  should be overwritten during a rebuild or deleted when the index is deleted, but currently are not

1. Delete corrupted (rebuild is not working) index from UI.
2. Create new index with the same name via UI.
3. The "new index" has the same data as the "old index" -  rebuild still not working.

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We will investigate and keep you informed of our progress.

**Comment by bkapustik** [comment]
Hello, this has been fixed in the PR #79 and released in the release v10.0.0
