### ISSUE TITLE
Feature: Rename application (on dashboard) from Search to Lucene Search

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-lucene#75]
**Is your feature request related to a problem? Please describe.**

Customers can use multiple search integrations (Lucene, Azure AI Search, Algolia) at the same time and for different purposes.

Today, if they do use multiple search integrations they will not be able to easily differentiate them on the administration dashboard because they are all named "Search".

**Describe the solution you'd like**

Instead, they should be renamed to match the integration.

![image](https://github.com/user-attachments/assets/9cd3e21a-491e-494e-95e5-b280c61d07db)

We should rename "Search" to "Lucene Search".

**Describe alternatives you've considered**

n/a

**Additional context**

This is a [one line update](https://github.com/Kentico/xperience-by-kentico-lucene/blob/v9.0.0/src/Kentico.Xperience.Lucene.Admin/UIPages/LuceneApplication.cs#L11).

**Comment by bkapustik** [comment]
This has been changed in #77 .
