### ISSUE TITLE
Command Line Database Installation Error: Mismatched Versions and Central Directory Problem

### ISSUE THREAD

**Issue by Rahul-Patel-17** [Kentico/xperience-by-kentico-lucene#80]
**Describe the bug**
I am encountering an error while attempting to create a database using the command line.

**To Reproduce**

1. Clone the repository.
2. Navigate to the dancinggoat folder.
3. Run the command dotnet restore.
4. Execute the command to install the database. (i.e, dotnet kentico-xperience-dbmanager -- -s "<sql_server_name>" -d "<database_name>" -a "<admin_password>" --hash-string-salt "<hash_string_salt>" --license-file "<license_file_path>")
5. See error.

**Expected behavior**
I expected the database to be installed successfully without any errors.

**Library Version**
The full version of the library or integration you experienced the issue with 29.3.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 130.0.6723.59 (Official Build) (64-bit)

**Additional context**
The error message I received is: "Error installing the database. Original message: Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory."

After encountering the error, the database is created but with database version '28.4.3'. While running the project, I am getting the exception: System.NotSupportedException: 'The database version '28.4.3' does not match the project version '29.3.3', please check your connection string.'

**Comment by seangwright** [comment]
Hello!

Your issue is unrelated to [the Lucene integration](https://github.com/Kentico/xperience-by-kentico-lucene) which provides search functionality for Xperience by Kentico projects. Please [contact support](https://community.kentico.com/support) with your issue.
