### ISSUE TITLE
RegexHtmlToTextWhiteSpace becoming obsolete

### ISSUE THREAD

**Issue by bpalmerzag** [Kentico/xperience-by-kentico-lucene#82]
It appears the next version of XbyK is getting rid of HTMLHelper.RegexHtmlToTextWhiteSpace.

'HTMLHelper.RegexHtmlToTextWhiteSpace' is obsolete: 'Property is deprecated and will be removed in the next version.'

Is there something it's being replaced with in XbyK? Is there something xperience-by-kentico-lucene would recommend using instead?

**Comment by bkapustik** [comment]
Hello, I am not sure what is the reason behind this change and what is it being be replaced for.
Until we know that, you can create your own regular expression: 

``` csharp
new Regex("\\s+");
```

Or use Kentico's `RegexHelper` which cashes regular expressions:

``` csharp
new Regex("\\s+", RegexOptions.IgnoreCase | RegexOptions.Compiled | RegexOptions.Singleline);
```

Or you can simply use .NET's built in option:

``` csharp
string result = string.Join(" ", input.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries));
```
